version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: smix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: smix
      POSTGRES_PASSWORD: smix
      POSTGRES_DB: smix
    ports:
      - "5432:5432"
    volumes:
      - smix_pg_data:/var/lib/postgresql/data

volumes:
  smix_pg_data:
